version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: greystone
      POSTGRES_USER: greystone
      POSTGRES_PASSWORD: greystone
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U greystone -d greystone"]
      interval: 5s
      timeout: 5s
      retries: 20
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # The FastAPI app reads DATABASE_URL from env
      DATABASE_URL: postgresql+psycopg://greystone:greystone@db:5432/greystone
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    restart: unless-stopped

volumes:
  pgdata:
